### ISSUE TITLE
Incorrect camel case in use.

### ISSUE THREAD

**Issue by danmarsden** [rogersegu/moodle-atto_c4l#1]
Moodle uses sentence case - please check your lang strings as some use camel case.

for example strings like:
$string['mystring'] = "My String";
should be:
$string['mystring'] = "My string";

Note: this is not a blocker for approval in the plugins db.

**Comment by rogersegu** [comment]
Thanks Dan! I just fixed it –except for the capital case in 'Atto' and in 'Components for learning', which are names.
